[project]
name = 'Multiverse-Resource-Allocation-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.cross-dimensional-trading]
path = 'contracts/cross-dimensional-trading.clar'
clarity_version = 2
epoch = 2.5

[contracts.inter-universal-resource-tracking_]
path = 'contracts/inter-universal-resource-tracking_.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
